[project]
name = "gemini"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "google-genai>=1.19.0",
    "python-dotenv>=1.1.0",
    "uvicorn>=0.34.3",
]
